//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Reference {
    
    /// <summary>
    /// txtElement control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox txtElement;
    
    /// <summary>
    /// rtCharacterClasses control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtCharacterClasses;
    
    /// <summary>
    /// rtCharacterEscapes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtCharacterEscapes;
    
    /// <summary>
    /// rtAnchors control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtAnchors;
    
    /// <summary>
    /// rtGroupingConstructs control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtGroupingConstructs;
    
    /// <summary>
    /// rtQuantifiers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtQuantifiers;
    
    /// <summary>
    /// rtBackreferenceConstructs control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtBackreferenceConstructs;
    
    /// <summary>
    /// rtAlternationConstructs control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtAlternationConstructs;
    
    /// <summary>
    /// rtSubstitutions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtSubstitutions;
    
    /// <summary>
    /// rtMiscellaneous control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls.ReferenceTable rtMiscellaneous;
    
    /// <summary>
    /// pnlNoResults control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlNoResults;
}
